export const personData = [
  {
    id: 1,
    name: "Kristo Kubasiewicz",
    age: 23,
    gender: "Male",
    dateOfBirth: "7/23/2023",
    area: "Mirpur",
    email: "kkubasiewicz0@vkontakte.ru",
    phonenumber: "752-232-2749",
    occupation: "Information Systems Manager",
  },
  {
    id: 2,
    name: "Jerrilee Coulthart",
    age: 88,
    gender: "Female",
    dateOfBirth: "7/24/2023",
    area: "Savar",
    email: "jcoulthart1@4shared.com",
    phonenumber: "795-296-0059",
    occupation: "Senior Financial Analyst",
  },
  {
    id: 3,
    name: "Karia Roarty",
    age: 23,
    gender: "Female",
    dateOfBirth: "5/6/2023",
    area: "Banani",
    email: "kroarty2@sciencedaily.com",
    phonenumber: "188-248-1227",
    occupation: "Physical Therapy Assistant",
  },
  {
    id: 4,
    name: "Michal Govan",
    age: 76,
    gender: "Male",
    dateOfBirth: "11/14/2023",
    area: "Gulshan",
    email: "mgovan3@ameblo.jp",
    phonenumber: "451-612-2059",
    occupation: "VP Product Management",
  },
  {
    id: 5,
    name: "Dennis Erb",
    age: 77,
    gender: "Male",
    dateOfBirth: "11/2/2023",
    area: "Dhanmondi",
    email: "derb4@ustream.tv",
    phonenumber: "596-969-4660",
    occupation: "Research Associate",
  },
  {
    id: 6,
    name: "Gearalt Stalf",
    age: 50,
    gender: "Male",
    dateOfBirth: "2/14/2024",
    area: "Mohakhali Dohs",
    email: "gstalf5@admin.ch",
    phonenumber: "919-187-1592",
    occupation: "Quality Control Specialist",
  },
  {
    id: 7,
    name: "Carlyn Leven",
    age: 30,
    gender: "Female",
    dateOfBirth: "5/7/2023",
    area: "Banani",
    email: "cleven6@goodreads.com",
    phonenumber: "880-943-8200",
    occupation: "Assistant Media Planner",
  },
  {
    id: 8,
    name: "Kata Eveleigh",
    age: 14,
    gender: "Female",
    dateOfBirth: "6/13/2023",
    area: "Gulshan",
    email: "keveleigh7@imgur.com",
    phonenumber: "901-586-6908",
    occupation: "VP Quality Control",
  },
  {
    id: 9,
    name: "Reg Stivers",
    age: 96,
    gender: "Male",
    dateOfBirth: "11/27/2023",
    area: "Mirpur",
    email: "rstivers8@wordpress.org",
    phonenumber: "284-177-2534",
    occupation: "Operator",
  },
  {
    id: 10,
    name: "Lyn Klampk",
    age: 93,
    gender: "Female",
    dateOfBirth: "5/15/2023",
    area: "Banani",
    email: "lklampk9@adobe.com",
    phonenumber: "909-468-4758",
    occupation: "Health Coach IV",
  },
];
